import UserProfile from "@/components/auth/UserProfile";

export const metadata = {
  title: "My-Profile IdeaVault",
  description: "Generated by kamal create next app",
};

const ProfilePage = () => {
  return (
    <div>
      <UserProfile />
    </div>
  );
};

export default ProfilePage;
