import MyIdeas from "@/components/myIdeas/MyIdeas";
import { allIdeasData } from "@/lib/data";

export const metadata = {
  title: "My-ideas IdeaVault",
  description: "Generated by kamal create next app",
};

const MyIdeasPage = async () => {
  const myIdeas = await allIdeasData();

  // console.log(myIdeas, "my idea");

  return (
    <div className="min-h-screen">
      <MyIdeas myIdeas={myIdeas} />
    </div>
  );
};

export default MyIdeasPage;
