import AddIdea from "@/components/ideasPage/AddIdea";

export const metadata = {
  title: "Add-idea IdeaVault",
  description: "Generated by kamal create next app",
};



const AddIdeaPage = () => {
  return (
    <div className="min-h-screen">
      <AddIdea />
    </div>
  );
};

export default AddIdeaPage;
