import RegisterForm from "@/components/auth/RegisterForm";

export const metadata = {
  title: "Register IdeaVault",
  description: "Generated by kamal create next app",
};



const SignUpPage = () => {
  return (
    <div
      className="min-h-screen bg-cover bg-center bg-no-repeat "
      style={{ backgroundImage: "url('/images/signup.png')" }}
    >
      <RegisterForm />
    </div>
  );
};

export default SignUpPage;
