import { Hind_Siliguri, Roboto } from "next/font/google";
import "./globals.css";



// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "600"]
})
const siliguri = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["400", "500", "600"]
})


export const metadata = {
  title: "Idea Vault",
  description: "Generated by kamal create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${siliguri.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
