// // google proxy forcefully connect
import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"])
// // =============================


import { Poppins, Urbanist, Hind_Siliguri, } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";



const urban = Urbanist({
  variable: "--font-urban",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],

})


const siliguri = Hind_Siliguri({
  variable: "--font-siliguri",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
})


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
});


export const metadata = {
  title: "IdeaVault",
  description: "Generated by kamal create next app",
};



export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${urban.variable}  ${poppins.variable} ${siliguri.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        <main className="min-h-screen">
          {children}
        </main>
        <ToastContainer />
      </body>
    </html>
  );
}
