import AllIdeas from "@/components/ideasPage/AllIdeas";

export const metadata = {
  title: "Ideas IdeaVault",
  description: "Generated by kamal create next app",
};



const AllIdeasPage = () => {
  return (
    <div className="min-h-screen">
      <AllIdeas />
    </div>
  );
};

export default AllIdeasPage;
