import AllIdeas from "@/components/ideasPage/AllIdeas";
import { allIdeasData } from "@/lib/data";

export const metadata = {
  title: "Ideas IdeaVault",
  description: "Generated by kamal create next app",
};



const AllIdeasPage =async () => {

  const ideas = await allIdeasData();
  return (
    <div className="min-h-screen">
      <AllIdeas initialIdeas={ideas} />
    </div>
  );
};

export default AllIdeasPage;

